site_name: EnronData
site_url: https://github.com/enrondata/enrondata
repo_url: https://github.com/enrondata/enrondata.git
docs_dir: docs
theme: readthedocs
pages:
# Introduction:
- ['index.md', 'Home', 'Enron Data']

## References:
- ['references/data.md', 'Data', 'Data']
- ['references/research.md', 'Research', 'Research']
- ['references/enron.md', 'Enron', 'Enron']

## About
- ['about.md', 'About', 'About']
